/* kc_data.js - v2.94 */

// v3.13: Full Board Expansion — maps event.key values to their _am audio assets.
const AUDIO_MAP = {

    // --- Numbers ---
    "0": "audio/numbers/num_0_am",
    "1": "audio/numbers/num_1_am",
    "2": "audio/numbers/num_2_am",
    "3": "audio/numbers/num_3_am",
    "4": "audio/numbers/num_4_am",
    "5": "audio/numbers/num_5_am",
    "6": "audio/numbers/num_6_am",
    "7": "audio/numbers/num_7_am",
    "8": "audio/numbers/num_8_am",
    "9": "audio/numbers/num_9_am",

    // --- Shift Symbols ---
    "!": "audio/symbols/sym_exclamation_point_am",
    "@": "audio/symbols/sym_at_symbol_am",
    "#": "audio/symbols/sym_hash_am",
    "$": "audio/symbols/sym_dollar_sign_am",
    "%": "audio/symbols/sym_percent_am",
    "^": "audio/symbols/sym_carat_am",
    "&": "audio/symbols/sym_ampersand_am",
    "*": "audio/symbols/sym_asterisk_am",
    "(": "audio/symbols/sym_open_parenthesis_am",
    ")": "audio/symbols/sym_closed_parenthesis_am",

    // --- Punctuation & Brackets ---
    "~":  "audio/symbols/sym_tilde_am",
    "`":  "audio/symbols/sym_back_tic_am",
    "-":  "audio/symbols/sym_dash_am",
    "_":  "audio/symbols/sym_Underscore_am",
    "=":  "audio/symbols/sym_equals_am",
    "+":  "audio/symbols/sym_plus_am",
    "[":  "audio/symbols/sym_open_bracket_am",
    "{":  "audio/symbols/sym_open_brace_am",
    "]":  "audio/symbols/sym_closed_bracket_am",
    "}":  "audio/symbols/sym_closed_brace_am",
    "\\": "audio/symbols/sym_backslash_am",
    "|":  "audio/symbols/sym_pipe_am",
    ";":  "audio/symbols/sym_semi_colonr_am",
    ":":  "audio/symbols/sym_colonr_am",
    "'":  "audio/symbols/sym_single_quote_am",
    '"':  "audio/symbols/sym_double_quote_am",
    ",":  "audio/symbols/sym_comma_am",
    "<":  "audio/symbols/sym_less_than_am",
    ".":  "audio/symbols/sym_period_am",
    ">":  "audio/symbols/sym_greater_than_am",
    "/":  "audio/symbols/sym_forward_slash_am",
    "?":  "audio/symbols/sym_question_mark_am",

    // --- Function Keys ---
    "F1":  "audio/modifiers/fun_1_am",
    "F2":  "audio/modifiers/fun_2_am",
    "F3":  "audio/modifiers/fun_3_am",
    "F4":  "audio/modifiers/fun_4_am",
    "F5":  "audio/modifiers/fun_5_am",
    "F6":  "audio/modifiers/fun_6_am",
    "F7":  "audio/modifiers/fun_7_am",
    "F8":  "audio/modifiers/fun_8_am",
    "F9":  "audio/modifiers/fun_9_am",
    "F10": "audio/modifiers/fun_10_am",
    "F11": "audio/modifiers/fun_11_am",
    "F12": "audio/modifiers/fun_12_am",

    // --- Modifiers & Navigation ---
    "Escape":    "audio/modifiers/mod_escape_am",
    "Tab":       "audio/modifiers/mod_tab_am",
    "CapsLock":  "audio/modifiers/mod_caps_lock_am",
    "Shift":     "audio/modifiers/mod_left_shift_am",
    "Control":   "audio/modifiers/mod_left_control_am",
    "Alt":       "audio/modifiers/mod_left_alt_am",
    "Insert":    "audio/modifiers/mod_insert_am",
    "Delete":    "audio/modifiers/mod_delete_am",
    "Home":      "audio/modifiers/mod_home_am",
    "End":       "audio/modifiers/mod_end_am",
    "PageUp":    "audio/modifiers/mod_page_up_am",
    "PageDown":  "audio/modifiers/mod_page_down_am",
    "ArrowUp":   "audio/modifiers/mod_up_arrow_am",
    "ArrowDown": "audio/modifiers/mod_down_arrow_am",
    "ArrowLeft": "audio/modifiers/mod_left_arrow_am",
    "ArrowRight":"audio/modifiers/mod_right_arrow_am"

};

const GAME_DATA = {
  config: {
    version: "2.94",
    debug_mode: true 
  },

  hubs: {
    0: {
      name: "Deck 0 Main Hub (Garbage Deck)",
      has_fabricator: true, 
      menu: [
        { label: "System Override", type: "mission", target_id: "D00-MISSION-REFLEX", desc: "Help Snippy repair ship systems by quickly typing single letters as they are called out." },
        { label: "Keyboard Commander", type: "mission", target_id: "D00-MISSION-RACE", desc: "Race against your rival, Commander Keyboard, by typing words as fast as you can to win." },
        { label: "Data Dump", type: "mission", target_id: "ARC-STREAM-01", desc: "Survival mode: Type a continuous stream of characters before the system overflows." },
        { label: "Arcade", type: "arcade", desc: "Access specialized typing drills and alternate missions." },
        { label: "Archive", type: "archive", desc: "Review your career stats, old story logs, and mission briefings." },
        { label: "Data Cache", type: "cache", desc: "Check your digital wallet and currency balances." },
        { label: "Engineering (R&D)", type: "engineering", desc: "Research and unlock permanent system upgrades." },
        { label: "System Fabricator", type: "fabricator", desc: "Purchase temporary boosts and single-use items." },
        { label: "Echo Chamber", type: "echoc", desc: "Safe zone: Practice your keyboard layout and explore menus without being scored." },
        { label: "Sound and Sight Settings", type: "settings", desc: "Adjust themes, text size, and ambient music." },
        { label: "Stay Out", type: "stay_out", desc: "For authorized personnel only. Opens the Dev Console with a verbal warning." },
        { label: "Save and Exit", type: "save_exit", desc: "Save your current progress and power down the terminal." }
      ]
    }
  },

  lessons: {
    "D00-01": { id: "D00-01", type: "tutorial", rank: "Cadet", name: "System Boot", briefing: "Kernel loaded. Connection to Deck 0 established. Welcome, User. Standard Protocol requires manual input to advance; press Enter to continue.", sequence: "" },
    "D00-02": { id: "D00-02", type: "tutorial", tutorial_action: "shortcut_drill", rank: "Cadet", name: "Intro Briefing", briefing: "Well, hello there! Welcome aboard! I’m Amelia. Let’s get you started with system calibration. You already know that Enter generally moves you forward, but let's talk about replaying audio. I know you'll want to hear my voice over and over. You can replay any character audio with Shift + Enter. Let's try that now.", audio_briefing: "audio/d00_tu_am_01.mp3", briefing_prompt: "Press Shift plus Enter to continue.", sequence: "", suppress_report: true },
    "D00-03": { id: "D00-03", type: "tutorial", rank: "Cadet", name: "Intro Success", briefing: "Hey! Good job. You really can follow orders. Now, normally that would replay the audio. Remember: Shift + Enter replays audio, while Enter skips ahead.", audio_briefing: "audio/d00_tu_am_02.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-04": { id: "D00-04", type: "tutorial", rank: "Cadet", name: "Mission Briefing", briefing: "Good job, cadet. We’ve got AI systems hallucinating, Comms is infected with a virus, and the Chrome Armada is approaching... and you stopped to buy a hologram of a cat. We sent out for the best, and that was presumably you. Better get you logged on.", audio_briefing: "audio/d00_tu_am_03.mp3", briefing_prompt: "Press Enter to continue.", sequence: "", force_prompt: true },
    "D00-05": { id: "D00-05", type: "tutorial", rank: "Cadet", name: "Meet Snippy", briefing: "Amelia: I am patching you into the ship’s core. Snippy, are you there? \n\nSnippy: Hi, I’m Snippy. I’m the ship. I don't do what you type... you type what I tell you. Right now, I need to verify that you are human with a biometric scan.", audio_briefing: "audio/d00_tu_mix_01.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-06": { id: "D00-06", type: "tutorial", rank: "Cadet", name: "Finger Placement", briefing: "Snippy: Security Protocol Alpha. I need to scan your index fingers. Place Left Index on F. Place Right Index on J. Feel for the small raised bumps on those keys. Anchor your hands.", audio_briefing: "audio/d00_tu_sys_01z.mp3", briefing_prompt: "Press Enter when ready.", sequence: "" },
    "D00-07": { id: "D00-07", type: "tutorial", rank: "Cadet", name: "Left Finger Scan", briefing: "Scanning... Let’s start with your left finger. Press F now.", audio_briefing: "audio/d00_tu_sys_02z.mp3", briefing_prompt: "Press F.", sequence: "f", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-08": { id: "D00-08", type: "tutorial", rank: "Cadet", name: "Right Finger Scan", briefing: "Good! Now for your right finger. Press J now.", audio_briefing: "audio/d00_tu_sys_03z.mp3", briefing_prompt: "Press J.", sequence: "j", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-09": { id: "D00-09", type: "tutorial", rank: "Cadet", name: "Re-Scan J", briefing: "Good. ... Oh wait. I forgot to save those files. Sorry, we need to do that again. Let’s start with J this time.", audio_briefing: "audio/d00_tu_sys_04z.mp3", briefing_prompt: "Press J.", sequence: "j", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-10": { id: "D00-10", type: "tutorial", rank: "Cadet", name: "Re-Scan F", briefing: "Great. Now your left finger. Press F now.", audio_briefing: "audio/d00_tu_sys_05z.mp3", briefing_prompt: "Press F.", sequence: "f", auto_start: true, suppress_report: true },
    "D00-11": { id: "D00-11", type: "tutorial", rank: "Cadet", name: "HR Paperwork", briefing: "Snippy: Identity Verified. \n\nAmelia: Oh good. You are scheduled to spend months in HR filling out paperwork. \n\nSnippy: Bring something to read while waiting for a notary public. \n\nAmelia: But thankfully, we have tasks to do. Let's try System Control.", audio_briefing: "audio/d00_tu_mix_02.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-12": { id: "D00-12", type: "tutorial", rank: "Cadet", name: "Systems Control Intro", briefing: "Amelia: Due to virus attacks, Snippy's routing is broken. \n\nSnippy: I tried to fire torpedoes and flushed the toilets on Deck 4 instead. \n\nAmelia: When Snippy calls a system, hit the key immediately. Fuel is F. Stabilizers is S. Drive is D. Auxiliary is A.", audio_briefing: "audio/d00_tu_mix_03.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-13": { id: "D00-13", type: "tutorial", rank: "Cadet", name: "Reflex: Fuel", briefing: "Snippy: Initiating Left Hand Override. ... Fuel.", audio_briefing: "audio/d00_tu_sys_cue_f1.mp3", briefing_prompt: "Type F.", sequence: "f", auto_start: true, suppress_report: true },
    "D00-14": { id: "D00-14", type: "tutorial", rank: "Cadet", name: "Reflex: Drive", briefing: "Drive.", audio_briefing: "audio/d00_tu_sys_cue_d1.mp3", briefing_prompt: "Type D.", sequence: "d", auto_start: true, suppress_report: true },
    "D00-15": { id: "D00-15", type: "tutorial", rank: "Cadet", name: "Reflex: Stabilizers", briefing: "Stabilizers.", audio_briefing: "audio/d00_tu_sys_cue_s1.mp3", briefing_prompt: "Type S.", sequence: "s", auto_start: true, suppress_report: true },
    "D00-16": { id: "D00-16", type: "tutorial", rank: "Cadet", name: "Reflex: Auxiliary", briefing: "Auxiliary.", audio_briefing: "audio/d00_tu_sys_cue_a1.mp3", briefing_prompt: "Type A.", sequence: "a", auto_start: true, suppress_report: true },
    "D00-17": { id: "D00-17", type: "tutorial", rank: "Cadet", name: "Reflex: Random", briefing: "Random Sequence Initiated...", sequence: "fdasdfsa", briefing_prompt: "Type the commands.", custom_cues: ["Fuel.", "Drive.", "Auxiliary.", "Stabilizers.", "Drive.", "Fuel.", "Stabilizers.", "Auxiliary."], audio_cues: ["audio/d00_tu_sys_cue_f1.mp3","audio/d00_tu_sys_cue_d1.mp3","audio/d00_tu_sys_cue_a1.mp3","audio/d00_tu_sys_cue_s1.mp3","audio/d00_tu_sys_cue_d1.mp3","audio/d00_tu_sys_cue_f1.mp3","audio/d00_tu_sys_cue_s1.mp3","audio/d00_tu_sys_cue_a1.mp3"], auto_start: true, suppress_report: true },
    "D00-18": { id: "D00-18", type: "tutorial", rank: "Cadet", name: "Reflex Success", briefing: "Snippy: Diagnostic Complete. Toilet flushing logic reset. \n\nAmelia: No really. Thank you.", audio_briefing: "audio/d00_tu_mix_04.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-19": { id: "D00-19", type: "tutorial", rank: "Cadet", name: "Code Breaking Intro", briefing: "Amelia: You are on Deck 0 (Garbage). We need to unlock the elevator. \n\nSnippy: The Captain set an easy password. Three words. Left hand only. I will read them, you type them and press Space.", audio_briefing: "audio/d00_tu_mix_05.mp3", briefing_prompt: "Press Enter to continue.", sequence: "" },
    "D00-20": { id: "D00-20", type: "tutorial", rank: "Cadet", name: "Word: Sad", briefing: "Accessing Mainframe. The first passkey is: Sad. S... A... D...", audio_briefing: "audio/d00_tu_sys_06z.mp3", briefing_prompt: "Type sad and press spacebar.", sequence: "sad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-21": { id: "D00-21", type: "tutorial", rank: "Cadet", name: "Word: Fad", briefing: "Passkey accepted. The second passkey is: Fad. F... A... D...", audio_briefing: "audio/d00_tu_sys_07z.mp3", briefing_prompt: "Type fad and press spacebar.", sequence: "fad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-22": { id: "D00-22", type: "tutorial", rank: "Cadet", name: "Word: Dad", briefing: "Passkey accepted. The final passkey is: Dad. D... A... D...", audio_briefing: "audio/d00_tu_sys_08z.mp3", briefing_prompt: "Type dad and press spacebar.", sequence: "dad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-23": { id: "D00-23", type: "tutorial", rank: "Cadet", name: "Code Error", briefing: "Snippy: Processing... Error. Checksum invalid. I might have read those in the wrong order. My apologies. Let's try reverse order. \n\nAmelia: Snippy! Focus!", audio_briefing: "audio/d00_tu_mix_06.mp3", briefing_prompt: "Type dad and press spacebar.", sequence: "dad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-25": { id: "D00-25", type: "tutorial", rank: "Cadet", name: "Retry: Fad", briefing: "Second word: Fad.", audio_briefing: "audio/d00_tu_sys_09z.mp3", briefing_prompt: "Type fad and press spacebar.", sequence: "fad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-26": { id: "D00-26", type: "tutorial", rank: "Cadet", name: "Retry: Sad", briefing: "Third word: Sad.", audio_briefing: "audio/d00_tu_sys_10z.mp3", briefing_prompt: "Type sad and press spacebar.", sequence: "sad ", auto_start: true, force_prompt: true, suppress_report: true },
    "D00-27": { id: "D00-27", type: "tutorial", rank: "Commander", name: "Victory", briefing: "Snippy: Access Granted. Blast doors opening. \n\nAmelia: Well done cadet! I'll see you on Deck 1.", audio_briefing: "audio/d00_tu_mix_07.mp3", sequence: "", go_to_hub: true },
    
    "D00-MISSION-REFLEX": {
      id: "D00-MISSION-REFLEX",
      name: "System Override: Reflex Calibration",
      generator: "reflex",
      params: { regionMode: 0, difficulty: 3 }
    },
    "D00-MISSION-RACE": {
      id: "D00-MISSION-RACE",
      name: "Keyboard Commander: Race",
      generator: "race",
      params: { regionMode: 0, difficulty: 3 }
    },
    "ARC-STREAM-01": {
      id: "ARC-STREAM-01",
      name: "Data Dump: Stream",
      generator: "stream",
      params: { regionMode: 6, difficulty: 5 }
    }
  },
  
  system_words: {
      "a": ["auxiliary", "armor", "access", "alert", "alpha"],
      "b": ["boosters", "ballistics", "bulkheads", "beacon"],
      "c": ["comms", "cargo", "cryogenics", "core"],
      "d": ["drive", "data", "deploy", "drone"],
      "e": ["emitters", "encryption"],
      "f": ["fuel", "fusion", "field", "flux"],
      "g": ["grid", "gear", "gate", "gauge", "golf"],
      "h": ["hull", "heat", "helm", "hatch", "hotel"],
      "i": ["ignition", "inertial", "infrared"],
      "j": ["jump", "jets", "junction", "jettison"],
      "k": ["kinetic", "kilo", "kit", "kilowatt"],
      "l": ["laser", "lock", "launch", "link"],
      "m": ["mainframe", "magnetics", "munitions", "monitors"],
      "n": ["navigation", "network", "neutrino", "node"],
      "o": ["oxygen", "optics", "override", "orbit"],
      "p": ["plasma", "propulsion", "probes", "payload"],
      "q": ["quantum", "quasar", "quarantine"],
      "r": ["radar", "reactor", "relays"],
      "s": ["stabilizers", "shields", "sensors", "scan"],
      "t": ["thrusters", "telemetry", "targeting", "tachyeon"],
      "u": ["uplink", "utilities", "ultraviolet", "uhf"],
      "v": ["velocity", "visuals", "vector", "vacuum"],
      "w": ["weapons", "warp", "waypoint", "waveform"],
      "x": ["xenon", "x_ray", "x_axis"],
      "y": ["yaw", "yield", "yoke", "y_axis"],
      "z": ["zenith", "zone", "zephyr", "z_axis"]
  },

  audio_bank: {
      "num_sn_0": "audio/numbers/zero_sn.mp3",
      "num_sn_1": "audio/numbers/one_sn.mp3",
      "num_sn_2": "audio/numbers/two_sn.mp3",
      "num_sn_3": "audio/numbers/three_sn.mp3",
      "num_sn_4": "audio/numbers/four_sn.mp3",
      "num_sn_5": "audio/numbers/five_sn.mp3",
      "num_sn_6": "audio/numbers/six_sn.mp3",
      "num_sn_7": "audio/numbers/seven_sn.mp3",
      "num_sn_8": "audio/numbers/eight_sn.mp3",
      "num_sn_9": "audio/numbers/nine_sn.mp3",
      "num_sn_10": "audio/numbers/ten_sn.mp3",
      "word_go_sn": "audio/words/go_sn.mp3",

      "char_a": "audio/alpha/char_a_ame.mp3", "char_b": "audio/alpha/char_b_ame.mp3", "char_c": "audio/alpha/char_c_ame.mp3",
      "char_d": "audio/alpha/char_d_ame.mp3", "char_e": "audio/alpha/char_e_ame.mp3", "char_f": "audio/alpha/char_f_ame.mp3",
      "char_g": "audio/alpha/char_g_ame.mp3", "char_h": "audio/alpha/char_h_ame.mp3", "char_i": "audio/alpha/char_i_ame.mp3",
      "char_j": "audio/alpha/char_j_ame.mp3", "char_k": "audio/alpha/char_k_ame.mp3", "char_l": "audio/alpha/char_l_ame.mp3",
      "char_m": "audio/alpha/char_m_ame.mp3", "char_n": "audio/alpha/char_n_ame.mp3", "char_o": "audio/alpha/char_o_ame.mp3",
      "char_p": "audio/alpha/char_p_ame.mp3", "char_q": "audio/alpha/char_q_ame.mp3", "char_r": "audio/alpha/char_r_ame.mp3",
      "char_s": "audio/alpha/char_s_ame.mp3", "char_t": "audio/alpha/char_t_ame.mp3", "char_u": "audio/alpha/char_u_ame.mp3",
      "char_v": "audio/alpha/char_v_ame.mp3", "char_w": "audio/alpha/char_w_ame.mp3", "char_x": "audio/alpha/char_x_ame.mp3",
      "char_y": "audio/alpha/char_y_ame.mp3", "char_z": "audio/alpha/char_z_ame.mp3",

      // Legacy System Cues (v2.66.1)
      "word_fuel": "audio/d00_tu_sys_cue_f1.mp3",
      "word_drive": "audio/d00_tu_sys_cue_d1.mp3",
      "word_stabilizers": "audio/d00_tu_sys_cue_s1.mp3",
      "word_auxiliary": "audio/d00_tu_sys_cue_a1.mp3",

      // Home Row Mappings (v2.66.2)
      "word_armor": "audio/words/armor_sn.mp3",
      "word_access": "audio/words/access_sn.mp3",
      "word_alert": "audio/words/alert_sn.mp3",
      "word_alpha": "audio/words/alpha_sn.mp3",
      "word_shields": "audio/words/shields_sn.mp3",
      "word_sensors": "audio/words/sensors_sn.mp3",
      "word_scan": "audio/words/scan_sn.mp3",
      "word_data": "audio/words/data_sn.mp3",
      "word_deploy": "audio/words/deploy_sn.mp3",
      "word_drone": "audio/words/drone_sn.mp3",
      "word_fusion": "audio/words/fusion_sn.mp3",
      "word_field": "audio/words/field_sn.mp3",
      "word_flux": "audio/words/flux_sn.mp3",
      "word_grid": "audio/words/grid_sn.mp3",
      "word_gear": "audio/words/gear_sn.mp3",
      "word_gate": "audio/words/gate_sn.mp3",
      "word_gauge": "audio/words/gauge_sn.mp3",
      "word_golf": "audio/words/golf_sn.mp3",
      "word_hull": "audio/words/hull_sn.mp3",
      "word_heat": "audio/words/heat_sn.mp3",
      "word_helm": "audio/words/helm_sn.mp3",
      "word_hatch": "audio/words/hatch_sn.mp3",
      "word_hotel": "audio/words/hotel_sn.mp3",
      "word_jump": "audio/words/jump_sn.mp3",
      "word_jets": "audio/words/jets_sn.mp3",
      "word_junction": "audio/words/junction_sn.mp3",
      "word_jettison": "audio/words/jettison_sn.mp3",
      "word_kinetic": "audio/words/kinetic_sn.mp3",
      "word_kilo": "audio/words/kilo_sn.mp3",
      "word_kit": "audio/words/kit_sn.mp3",
      "word_kilowatt": "audio/words/kilowatt_sn.mp3",
      "word_laser": "audio/words/laser_sn.mp3",
      "word_lock": "audio/words/lock_sn.mp3",
      "word_launch": "audio/words/launch_sn.mp3",
      "word_link": "audio/words/link_sn.mp3",

      // Junie Racing Mappings (v2.68)
      "word_ju_war": "audio/words/war_ju.mp3",
      "word_ju_star": "audio/words/star_ju.mp3",
      "word_ju_data": "audio/words/data_ju.mp3",
      "word_ju_gate": "audio/words/gate_ju.mp3",
      "word_ju_gear": "audio/words/gear_ju.mp3",
      "word_ju_dart": "audio/words/dart_ju.mp3",
      "word_ju_raft": "audio/words/Raft_ju.mp3",
      "word_ju_fade": "audio/words/fade_ju.mp3",
      "word_ju_fast": "audio/words/fast_ju.mp3",
      "word_ju_deaf": "audio/words/deaf_ju.mp3",
      "word_ju_draw": "audio/words/draw_ju.mp3",
      "word_ju_drag": "audio/words/drag_ju.mp3",
      "word_ju_fret": "audio/words/fret_ju.mp3",
      "word_ju_seat": "audio/words/seat_ju.mp3",
      "word_ju_feed": "audio/words/feed_ju.mp3",
      "word_ju_rate": "audio/words/rate_ju.mp3",
      "word_ju_safe": "audio/words/safe_ju.mp3",
      "word_ju_date": "audio/words/date_ju.mp3",
      "word_ju_radar": "audio/words/radar_ju.mp3",
      "word_ju_hull": "audio/words/hull_ju.mp3",
      "word_ju_loop": "audio/words/loop_ju.mp3",
      "word_ju_hook": "audio/words/hook_ju.mp3",
      "word_ju_pull": "audio/words/pull_ju.mp3",
      "word_ju_kill": "audio/words/kill_ju.mp3",
      "word_ju_polo": "audio/words/polo_ju.mp3",
      "word_ju_yolk": "audio/words/yolk_ju.mp3",
      "word_ju_pill": "audio/words/pill_ju.mp3",
      "word_ju_hoop": "audio/words/hoop_ju.mp3",
      "word_ju_look": "audio/words/look_ju.mp3",
      "word_ju_hill": "audio/words/hill_ju.mp3",
      "word_ju_oil": "audio/words/oil_ju.mp3",
      "word_ju_joy": "audio/words/joy_ju.mp3",
      "word_ju_hop": "audio/words/hop_ju.mp3",
      "word_ju_pool": "audio/words/pool_ju.mp3",
      "word_ju_ploy": "audio/words/ploy_ju.mp3",
      "word_ju_pop": "audio/words/pop_ju.mp3",
      "word_ju_lip": "audio/words/lip_ju.mp3",
      "word_ju_pup": "audio/words/pup_ju.mp3",
      "word_ju_holy": "audio/words/holy_ju.mp3",
      "word_ju_ship": "audio/words/ship_ju.mp3",
      "word_ju_warp": "audio/words/warp_ju.mp3",
      "word_ju_pulse": "audio/words/pulse_ju.mp3",
      "word_ju_fleet": "audio/words/fleet_ju.mp3",
      "word_ju_phase": "audio/words/phase_ju.mp3",
      "word_ju_flare": "audio/words/flare_ju.mp3",
      "word_ju_drift": "audio/words/drift_ju.mp3",
      "word_ju_rogue": "audio/words/rogue_ju.mp3",
      "word_ju_surge": "audio/words/surge_ju.mp3",
      "word_ju_error": "audio/words/error_ju.mp3",
      "word_ju_laser": "audio/words/laser_ju.mp3",
      "word_ju_pilot": "audio/words/pilot_ju.mp3",
      "word_ju_port": "audio/words/port_ju.mp3",
      "word_ju_ray": "audio/words/ray_ju.mp3",
      "word_ju_grid": "audio/words/grid_ju.mp3",
      "word_ju_fuel": "audio/words/fuel_ju.mp3",
      "word_ju_heat": "audio/words/heat_ju.mp3",
      "word_ju_alert": "audio/words/alert_ju.mp3",
      "word_ju_target": "audio/words/target_ju.mp3",
      "word_ju_defeat": "audio/words/defeat_ju.mp3",
      "word_ju_dagger": "audio/words/dagger_ju.mp3",
      "word_ju_drafts": "audio/words/drafts_ju.mp3",
      "word_ju_states": "audio/words/states_ju.mp3",
      "word_ju_resets": "audio/words/resets_ju.mp3",
      "word_ju_grades": "audio/words/grades_ju.mp3",
      "word_ju_faster": "audio/words/faster_ju.mp3",
      "word_ju_stared": "audio/words/stared_ju.mp3",
      "word_ju_radars": "audio/words/radars_ju.mp3",
      "word_ju_watered": "audio/words/watered_ju.mp3",
      "word_ju_stages": "audio/words/stages_ju.mp3",
      "word_ju_trades": "audio/words/trades_ju.mp3",
      "word_ju_fatter": "audio/words/fatter_ju.mp3",
      "word_ju_wastes": "audio/words/wastes_ju.mp3",
      "word_ju_starter": "audio/words/starter_ju.mp3",
      "word_ju_drafted": "audio/words/drafted_ju.mp3",
      "word_ju_deadest": "audio/words/deadest_ju.mp3",
      "word_ju_loophole": "audio/words/loophole_ju.mp3",
      "word_ju_lollipop": "audio/words/lollipop_ju.mp3",
      "word_ju_pullup": "audio/words/pullup_ju.mp3",
      "word_ju_lookup": "audio/words/lookup_ju.mp3",
      "word_ju_killjoy": "audio/words/killjoy_ju.mp3",
      "word_ju_holly": "audio/words/holly_ju.mp3",
      "word_ju_puppy": "audio/words/puppy_ju.mp3",
      "word_ju_kooky": "audio/words/kooky_ju.mp3",
      "word_ju_jolly": "audio/words/jolly_ju.mp3",
      "word_ju_lolly": "audio/words/lolly_ju.mp3",
      "word_ju_popup": "audio/words/popup_ju.mp3",
      "word_ju_yuppy": "audio/words/yuppy_ju.mp3",
      "word_ju_loopy": "audio/words/loopy_ju.mp3",
      "word_ju_hooky": "audio/words/hooky_ju.mp3",
      "word_ju_hilly": "audio/words/hilly_ju.mp3",
      "word_ju_poppy": "audio/words/poppy_ju.mp3",
      "word_ju_hippo": "audio/words/hippo_ju.mp3",
      "word_ju_polio": "audio/words/polio_ju.mp3",
      "word_ju_shields": "audio/words/shields_ju.mp3",
      "word_ju_strike": "audio/words/strike_ju.mp3",
      "word_ju_portal": "audio/words/portal_ju.mp3",
      "word_ju_stealth": "audio/words/stealth_ju.mp3",
      "word_ju_thrust": "audio/words/thrust_ju.mp3",
      "word_ju_hostile": "audio/words/hostile_ju.mp3",
      "word_ju_flight": "audio/words/flight_ju.mp3",
      "word_ju_patrol": "audio/words/patrol_ju.mp3",
      "word_ju_repair": "audio/words/repair_ju.mp3",
      "word_ju_filter": "audio/words/filter_ju.mp3",
      "word_ju_deploy": "audio/words/deploy_ju.mp3",
      "word_ju_thruster": "audio/words/thruster_ju.mp3",
      "word_ju_phaser": "audio/words/phaser_ju.mp3",
      "word_ju_stellar": "audio/words/stellar_ju.mp3",
      "word_ju_upgrade": "audio/words/upgrade_ju.mp3",
      "word_ju_fighter": "audio/words/fighter_ju.mp3",
      "word_ju_outpost": "audio/words/outpost_ju.mp3",
      "word_ju_asteroid": "audio/words/asteroid_ju.mp3",
      "word_ju_digital": "audio/words/digital_ju.mp3",
      "word_ju_payload": "audio/words/payload_ju.mp3",
      // Pure Home Row Mappings (v2.69.1)
      "word_ju_sad": "audio/words/sad_ju.mp3",
      "word_ju_dad": "audio/words/dad_ju.mp3",
      "word_ju_fad": "audio/words/fad_ju.mp3",
      "word_ju_gas": "audio/words/gas_ju.mp3",
      "word_ju_sag": "audio/words/sag_ju.mp3",
      "word_ju_add": "audio/words/add_ju.mp3",
      "word_ju_gag": "audio/words/gag_ju.mp3",
      "word_ju_fads": "audio/words/fads_ju.mp3",
      "word_ju_dash": "audio/words/dash_ju.mp3",
      "word_ju_flash": "audio/words/flash_ju.mp3",
      "word_ju_hall": "audio/words/hall_ju.mp3",
      "word_ju_half": "audio/words/half_ju.mp3",
      "word_ju_glad": "audio/words/glad_ju.mp3",
      "word_ju_glass": "audio/words/glass_ju.mp3",
      "word_ju_flag": "audio/words/flag_ju.mp3",
      "word_ju_fall": "audio/words/fall_ju.mp3",
      "word_ju_lag": "audio/words/lag_ju.mp3",
      "word_ju_ask": "audio/words/ask_ju.mp3",
      "word_ju_ash": "audio/words/ash_ju.mp3",
      "word_ju_gash": "audio/words/gash_ju.mp3",
      "word_ju_flask": "audio/words/flask_ju.mp3",
      "word_ju_slash": "audio/words/slash_ju.mp3",
      "word_ju_salad": "audio/words/salad_ju.mp3",
      "word_ju_alas": "audio/words/alas_ju.mp3",
      // Bottom & Home Row Mappings (v2.74)
      "word_ju_ace": "audio/words/ace_ju.mp3",
      "word_ju_axe": "audio/words/axe_ju.mp3",
      "word_ju_bad": "audio/words/bad_ju.mp3",
      "word_ju_bag": "audio/words/bag_ju.mp3",
      "word_ju_base": "audio/words/base_ju.mp3",
      "word_ju_bead": "audio/words/bead_ju.mp3",
      "word_ju_bed": "audio/words/bed_ju.mp3",
      "word_ju_beg": "audio/words/beg_ju.mp3",
      "word_ju_cab": "audio/words/cab_ju.mp3",
      "word_ju_cage": "audio/words/cage_ju.mp3",
      "word_ju_case": "audio/words/case_ju.mp3",
      "word_ju_cave": "audio/words/cave_ju.mp3",
      "word_ju_dab": "audio/words/dab_ju.mp3",
      "word_ju_face": "audio/words/face_ju.mp3",
      "word_ju_save": "audio/words/save_ju.mp3",
      "word_ju_scab": "audio/words/scab_ju.mp3",
      "word_ju_vex": "audio/words/vex_ju.mp3",
      "word_ju_zed": "audio/words/zed_ju.mp3",
      "word_ju_access": "audio/words/access_ju.mp3",
      "word_ju_adverb": "audio/words/adverb_ju.mp3",
      "word_ju_baggage": "audio/words/baggage_ju.mp3",
      "word_ju_beaver": "audio/words/beaver_ju.mp3",
      "word_ju_brave": "audio/words/brave_ju.mp3",
      "word_ju_excess": "audio/words/excess_ju.mp3",
      "word_ju_savage": "audio/words/savage_ju.mp3",
      "word_ju_him": "audio/words/him_ju.mp3",
      "word_ju_hum": "audio/words/hum_ju.mp3",
      "word_ju_inn": "audio/words/inn_ju.mp3",
      "word_ju_ion": "audio/words/ion_ju.mp3",
      "word_ju_join": "audio/words/join_ju.mp3",
      "word_ju_kin": "audio/words/kin_ju.mp3",
      "word_ju_link": "audio/words/link_ju.mp3",
      "word_ju_lion": "audio/words/lion_ju.mp3",
      "word_ju_milk": "audio/words/milk_ju.mp3",
      "word_ju_monk": "audio/words/monk_ju.mp3",
      "word_ju_moon": "audio/words/moon_ju.mp3",
      "word_ju_noun": "audio/words/noun_ju.mp3",
      "word_ju_no": "audio/words/no_ju.mp3",
      "word_ju_nun": "audio/words/nun_ju.mp3",
      "word_ju_on": "audio/words/on_ju.mp3",
      "word_ju_million": "audio/words/million_ju.mp3",
      "word_ju_minion": "audio/words/minion_ju.mp3",
      "word_ju_onion": "audio/words/onion_ju.mp3",
      "word_ju_opinion": "audio/words/opinion_j_ju.mp3",
      "word_ju_unhook": "audio/words/unhook_ju.mp3",
      "word_ju_union": "audio/words/union_ju.mp3",
      "word_ju_back": "audio/words/back_ju.mp3",
      "word_ju_bank": "audio/words/bank_ju.mp3",
      "word_ju_bang": "audio/words/bang_ju.mp3",
      "word_ju_beam": "audio/words/beam_ju.mp3",
      "word_ju_black": "audio/words/black_ju.mp3",
      "word_ju_blue": "audio/words/blue_ju.mp3",
      "word_ju_bone": "audio/words/bone_ju.mp3",
      "word_ju_book": "audio/words/book_ju.mp3",
      "word_ju_call": "audio/words/call_ju.mp3",
      "word_ju_can": "audio/words/can_ju.mp3",
      "word_ju_cloud": "audio/words/cloud_ju.mp3",
      "word_ju_coin": "audio/words/coin_ju.mp3",
      "word_ju_cold": "audio/words/cold_ju.mp3",
      "word_ju_come": "audio/words/come_ju.mp3",
      "word_ju_dance": "audio/words/dance_ju.mp3",
      "word_ju_done": "audio/words/done_ju.mp3",
      "word_ju_each": "audio/words/each_ju.mp3",
      "word_ju_fact": "audio/words/fact_ju.mp3",
      "word_ju_film": "audio/words/film_ju.mp3",
      "word_ju_five": "audio/words/five_ju.mp3",
      "word_ju_found": "audio/words/found_ju.mp3",
      "word_ju_game": "audio/words/game_ju.mp3",
      "word_ju_give": "audio/words/give_ju.mp3",
      "word_ju_gone": "audio/words/gone_ju.mp3",
      "word_ju_hand": "audio/words/hand_ju.mp3",
      "word_ju_have": "audio/words/have_ju.mp3",
      "word_ju_home": "audio/words/home_ju.mp3",
      "word_ju_kind": "audio/words/kind_ju.mp3",
      "word_ju_land": "audio/words/land_ju.mp3",
      "word_ju_long": "audio/words/long_ju.mp3",
      "word_ju_love": "audio/words/love_ju.mp3",
      "word_ju_made": "audio/words/made_ju.mp3",
      "word_ju_mind": "audio/words/mind_ju.mp3",
      "word_ju_miss": "audio/words/miss_ju.mp3",
      "word_ju_once": "audio/words/once_ju.mp3",
      "word_ju_small": "audio/words/small_ju.mp3",
      "word_ju_soon": "audio/words/soon_ju.mp3",
      "word_ju_sound": "audio/words/sound_ju.mp3",
      "word_ju_voice": "audio/words/voice_ju.mp3",
      "word_ju_balance": "audio/words/balance_ju.mp3",
      "word_ju_become": "audio/words/become_ju.mp3",
      "word_ju_believe": "audio/words/believe_ju.mp3",
      "word_ju_business": "audio/words/business_ju.mp3",
      "word_ju_abundance": "audio/words/abundance_ju.mp3",
      "word_ju_available": "audio/words/available_ju.mp3",
      "word_ju_balloon": "audio/words/balloon_ju.mp3",
      "word_ju_banana": "audio/words/banana_ju.mp3",
      "word_ju_canvas": "audio/words/canvas_ju.mp3",
      "word_ju_change": "audio/words/change_ju.mp3",
      "word_ju_choice": "audio/words/choice_ju.mp3",
      "word_ju_cinema": "audio/words/cinema_ju.mp3",
      "word_ju_climax": "audio/words/climax_ju.mp3",
      "word_ju_cocoon": "audio/words/cocoon_ju.mp3",
      "word_ju_common": "audio/words/common_ju.mp3",
      "word_ju_convex": "audio/words/convex_ju.mp3",
      "word_ju_cousin": "audio/words/cousin_ju.mp3",
      "word_ju_damage": "audio/words/damage_ju.mp3",
      "word_ju_decimal": "audio/words/decimal_ju.mp3",
      "word_ju_domain": "audio/words/domain_ju.mp3",
      "word_ju_double": "audio/words/double_ju.mp3",
      "word_ju_evidence": "audio/words/evidence_ju.mp3",
      "word_ju_finish": "audio/words/finish_ju.mp3",
      "word_ju_global": "audio/words/globalju.mp3",
      "word_ju_handle": "audio/words/handle_ju.mp3",
      "word_ju_humane": "audio/words/humane_ju.mp3",
      "word_ju_immune": "audio/words/immune_ju.mp3",
      "word_ju_island": "audio/words/island_ju.mp3",
      "word_ju_jungle": "audio/words/jungle_ju.mp3",
      "word_ju_launch": "audio/words/launch_ju.mp3",
      "word_ju_legend": "audio/words/legend_ju.mp3",
      "word_ju_lesson": "audio/words/lesson_ju.mp3",
      "word_ju_manage": "audio/words/manage_ju.mp3",
      "word_ju_middle": "audio/words/middle_ju.mp3",
      "word_ju_mission": "audio/words/mission_ju.mp3",
      "word_ju_muscle": "audio/words/muscle_ju.mp3",
      "word_ju_nibble": "audio/words/nibble_ju.mp3",
      "word_ju_nozzle": "audio/words/nozzle_ju.mp3",
      "word_ju_online": "audio/words/online_ju.mp3",
      "word_ju_login": "audio/words/login_ju.mp3",
      "word_ju_second": "audio/words/second_ju.mp3",
      "word_ju_signal": "audio/words/signal_ju.mp3",
      "word_ju_social": "audio/words/social_ju.mp3",
      "word_ju_sudden": "audio/words/sudden_ju.mp3",
      "word_ju_unfold": "audio/words/unfold_ju.mp3",
      "word_ju_usable": "audio/words/usable_ju.mp3",
      "word_ju_visual": "audio/words/visual_ju.mp3",
      "word_ju_than": "audio/words/than_ju.mp3",
      "word_ju_them": "audio/words/them_ju.mp3",
      "word_ju_then": "audio/words/then_ju.mp3",
      "word_ju_the": "audio/words/the_ju.mp3",
      // Mechanical Keyboard Clicks (v2.71)
      "sfx_key_1": "audio/sfx/key1.mp3",
      "sfx_key_2": "audio/sfx/key2.mp3",
      "sfx_key_3": "audio/sfx/key3.mp3",
      "sfx_key_4": "audio/sfx/key4.mp3",
      "sfx_key_5": "audio/sfx/key5.mp3",
      "sfx_key_6": "audio/sfx/key6.mp3",
      "sfx_key_7": "audio/sfx/key7.mp3",
      "ck_char_a": "audio/alpha/char_a_ck.mp3", "ck_char_b": "audio/alpha/char_b_ck.mp3", "ck_char_c": "audio/alpha/char_c_ck.mp3",
      "ck_char_d": "audio/alpha/char_d_ck.mp3", "ck_char_e": "audio/alpha/char_e_ck.mp3", "ck_char_f": "audio/alpha/char_f_ck.mp3",
      "ck_char_g": "audio/alpha/char_g_ck.mp3", "ck_char_h": "audio/alpha/char_h_ck.mp3", "ck_char_i": "audio/alpha/char_i_ck.mp3",
      "ck_char_j": "audio/alpha/char_j_ck.mp3", "ck_char_k": "audio/alpha/char_k_ck.mp3", "ck_char_l": "audio/alpha/char_l_ck.mp3",
      "ck_char_m": "audio/alpha/char_m_ck.mp3", "ck_char_n": "audio/alpha/char_n_ck.mp3", "ck_char_o": "audio/alpha/char_o_ck.mp3",
      "ck_char_p": "audio/alpha/char_p_ck.mp3", "ck_char_q": "audio/alpha/char_q_ck.mp3", "ck_char_r": "audio/alpha/char_r_ck.mp3",
      "ck_char_s": "audio/alpha/char_s_ck.mp3", "ck_char_t": "audio/alpha/char_t_ck.mp3", "ck_char_u": "audio/alpha/char_u_ck.mp3",
      "ck_char_v": "audio/alpha/char_v_ck.mp3", "ck_char_w": "audio/alpha/char_w_ck.mp3", "ck_char_x": "audio/alpha/char_x_ck.mp3",
      "ck_char_y": "audio/alpha/char_y_ck.mp3", "ck_char_z": "audio/alpha/char_z_ck.mp3",

      "mod_escape_am": "audio/modifiers/mod_escape_am.mp3", "mod_escape_ame": "audio/modifiers/mod_escape_ame.mp3",
      "mod_tab_am": "audio/modifiers/mod_tab_am.mp3", "mod_tab_ame": "audio/modifiers/mod_tab_ame.mp3",
      "mod_caps_lock_am": "audio/modifiers/mod_caps_lock_am.mp3", "mod_caps_lock_ame": "audio/modifiers/mod_caps_lock_ame.mp3",
      "mod_left_shift_am": "audio/modifiers/mod_left_shift_am.mp3", "mod_left_shift_ame": "audio/modifiers/mod_left_shift_ame.mp3",
      "mod_left_control_am": "audio/modifiers/mod_left_control_am.mp3", "mod_left_control_ame": "audio/modifiers/mod_left_control_ame.mp3",
      "mod_left_alt_am": "audio/modifiers/mod_left_alt_am.mp3", "mod_left_alt_ame": "audio/modifiers/mod_left_alt_ame.mp3",
      "mod_function_am": "audio/modifiers/mod_function_am.mp3", "mod_function_ame": "audio/modifiers/mod_function_ame.mp3",
      "mod_backspace_ame": "audio/modifiers/mod_backspace_ame.mp3", "mod_backspace_amee": "audio/modifiers/mod_backspace_amee.mp3",
      "mod_enter_ame": "audio/modifiers/mod_enter_ame.mp3", "mod_enter_amee": "audio/modifiers/mod_enter_amee.mp3",
      "mod_right_shift_ame": "audio/modifiers/mod_right_shift_ame.mp3", "mod_right_shift_amee": "audio/modifiers/mod_right_shift_amee.mp3",
      "mod_right_control_ame": "audio/modifiers/mod_right_control_ame.mp3", "mod_right_control_amee": "audio/modifiers/mod_right_control_amee.mp3",
      "mod_right_alt_ame": "audio/modifiers/mod_right_alt_ame.mp3", "mod_right_alt_amee": "audio/modifiers/mod_right_alt_amee.mp3",

      "sym_tilde_am": "audio/symbols/sym_tilde_am.mp3", "sym_tilde_ame": "audio/symbols/sym_tilde_ame.mp3",
      "sym_back_tic_am": "audio/symbols/sym_back_tic_am.mp3", "sym_back_tic_ame": "audio/symbols/sym_back_tic_ame.mp3",
      "sym_spacebar_am": "audio/symbols/sym_spacebar_am.mp3", "sym_spacebar_ame": "audio/symbols/sym_spacebar_ame.mp3",
      "sym_semi_colonr_am": "audio/symbols/sym_semi_colonr_am.mp3", "sym_semi_colonr_ame": "audio/symbols/sym_semi_colonr_ame.mp3",
      "sym_colonr_am": "audio/symbols/sym_colonr_am.mp3", "sym_colonr_ame": "audio/symbols/sym_colonr_ame.mp3",
      "sym_single_quote_am": "audio/symbols/sym_single_quote_am.mp3", "sym_single_quote_ame": "audio/symbols/sym_single_quote_ame.mp3",
      "sym_double_quote_am": "audio/symbols/sym_double_quote_am.mp3", "sym_double_quote_ame": "audio/symbols/sym_double_quote_ame.mp3",
      "sym_comma_am": "audio/symbols/sym_comma_am.mp3", "sym_comma_ame": "audio/symbols/sym_comma_ame.mp3",
      "sym_period_am": "audio/symbols/sym_period_am.mp3", "sym_period_ame": "audio/symbols/sym_period_ame.mp3",
      "sym_forward_slash_am": "audio/symbols/sym_forward_slash_am.mp3", "sym_forward_slash_ame": "audio/symbols/sym_forward_slash_ame.mp3",
      "sym_question_mark_am": "audio/symbols/sym_question_mark_am.mp3", "sym_question_mark_ame": "audio/symbols/sym_question_mark_ame.mp3",
      "sym_less_than_am": "audio/symbols/sym_less_than_am.mp3", "sym_less_than_ame": "audio/symbols/sym_less_than_ame.mp3",
      "sym_greater_than_am": "audio/symbols/sym_greater_than_am.mp3", "sym_greater_than_ame": "audio/symbols/sym_greater_than_ame.mp3",
      "sym_dash_am": "audio/symbols/sym_dash_am.mp3", "sym_dash_ame": "audio/symbols/sym_dash_ame.mp3",
      "sym_Underscore_am": "audio/symbols/sym_Underscore_am.mp3", "sym_Underscore_ame": "audio/symbols/sym_Underscore_ame.mp3",
      "sym_equals_am": "audio/symbols/sym_equals_am.mp3", "sym_equals_ame": "audio/symbols/sym_equals_ame.mp3",
      "sym_plus_am": "audio/symbols/sym_plus_am.mp3", "sym_plus_ame": "audio/symbols/sym_plus_ame.mp3",
      "sym_open_bracket_am": "audio/symbols/sym_open_bracket_am.mp3", "sym_open_bracket_ame": "audio/symbols/sym_open_bracket_ame.mp3",
      "sym_closed_bracket_am": "audio/symbols/sym_closed_bracket_am.mp3", "sym_closed_bracket_ame": "audio/symbols/sym_closed_bracket_ame.mp3",
      "sym_open_brace_am": "audio/symbols/sym_open_brace_am.mp3", "sym_open_brace_ame": "audio/symbols/sym_open_brace_ame.mp3",
      "sym_closed_brace_am": "audio/symbols/sym_closed_brace_am.mp3", "sym_closed_brace_ame": "audio/symbols/sym_closed_brace_ame.mp3",
      "sym_backslash_am": "audio/symbols/sym_backslash_am.mp3", "sym_backslash_ame": "audio/symbols/sym_backslash_ame.mp3",
      "sym_pipe_am": "audio/symbols/sym_pipe_am.mp3", "sym_pipe_ame": "audio/symbols/sym_pipe_ame.mp3",

      // --- DYNAMIC CHARACTER ALIASES ---
      
      // Numbers
      "char_1": "audio/numbers/num_1_ame.mp3", "char_2": "audio/numbers/num_2_ame.mp3", "char_3": "audio/numbers/num_3_ame.mp3",
      "char_4": "audio/numbers/num_4_ame.mp3", "char_5": "audio/numbers/num_5_ame.mp3", "char_6": "audio/numbers/num_6_ame.mp3",
      "char_7": "audio/numbers/num_7_ame.mp3", "char_8": "audio/numbers/num_8_ame.mp3", "char_9": "audio/numbers/num_9_ame.mp3",
      "char_0": "audio/numbers/num_0_ame.mp3",
      
      // Core Symbols
      "char_,": "audio/symbols/sym_comma_ame.mp3", "char_.": "audio/symbols/sym_period_ame.mp3", "char_ ": "audio/symbols/sym_spacebar_ame.mp3",
      "char_~": "audio/symbols/sym_tilde_ame.mp3", "char_`": "audio/symbols/sym_back_tic_ame.mp3", "char_;": "audio/symbols/sym_semi_colonr_ame.mp3",
      "char_:": "audio/symbols/sym_colonr_ame.mp3", "char_'": "audio/symbols/sym_single_quote_ame.mp3", "char_\"": "audio/symbols/sym_double_quote_ame.mp3",
      "char_/": "audio/symbols/sym_forward_slash_ame.mp3", "char_?": "audio/symbols/sym_question_mark_ame.mp3", "char_&lt;": "audio/symbols/sym_less_than_ame.mp3",
      "char_&gt;": "audio/symbols/sym_greater_than_ame.mp3", "char_-": "audio/symbols/sym_dash_ame.mp3", "char__": "audio/symbols/sym_Underscore_ame.mp3",
      "char_=": "audio/symbols/sym_equals_ame.mp3", "char_+": "audio/symbols/sym_plus_ame.mp3", "char_[": "audio/symbols/sym_open_bracket_ame.mp3",
      "char_]": "audio/symbols/sym_closed_bracket_ame.mp3", "char_{": "audio/symbols/sym_open_brace_ame.mp3", "char_}": "audio/symbols/sym_closed_brace_ame.mp3",
      "char_\\": "audio/symbols/sym_backslash_ame.mp3", "char_|": "audio/symbols/sym_pipe_ame.mp3",
      
      // Shifted Number Row Symbols (v2.6.0)
      "char_!": "audio/symbols/sym_exclamation_point_ame.mp3", "char_@": "audio/symbols/sym_at_symbol_ame.mp3", "char_#": "audio/symbols/sym_hash_ame.mp3",
      "char_$": "audio/symbols/sym_dollar_sign_ame.mp3", "char_%": "audio/symbols/sym_percent_ame.mp3", "char_^": "audio/symbols/sym_carat_ame.mp3",
      "char_&": "audio/symbols/sym_ampersand_ame.mp3", "char_*": "audio/symbols/sym_asterisk_ame.mp3", "char_(": "audio/symbols/sym_open_parenthesis_ame.mp3",
      "char_)": "audio/symbols/sym_closed_parenthesis_ame.mp3",
      
      // Modifiers & Navigation (v2.6.0)
      "char_escape": "audio/modifiers/mod_escape_ame.mp3", "char_tab": "audio/modifiers/mod_tab_ame.mp3", "char_capslock": "audio/modifiers/mod_caps_lock_ame.mp3",
      "char_shift": "audio/modifiers/mod_left_shift_ame.mp3", "char_control": "audio/modifiers/mod_left_control_ame.mp3", "char_alt": "audio/modifiers/mod_left_alt_ame.mp3",
      "char_backspace": "audio/modifiers/mod_backspace_ame.mp3", "char_enter": "audio/modifiers/mod_enter_ame.mp3", "char_f1": "audio/modifiers/fun_1_ame.mp3",
      "char_f2": "audio/modifiers/fun_2_ame.mp3", "char_f3": "audio/modifiers/fun_3_ame.mp3", "char_f4": "audio/modifiers/fun_4_ame.mp3",
      "char_f5": "audio/modifiers/fun_5_ame.mp3", "char_f6": "audio/modifiers/fun_6_ame.mp3", "char_f7": "audio/modifiers/fun_7_ame.mp3",
      "char_f8": "audio/modifiers/fun_8_ame.mp3", "char_f9": "audio/modifiers/fun_9_ame.mp3", "char_f10": "audio/modifiers/fun_10_ame.mp3",
      "char_f11": "audio/modifiers/fun_11_ame.mp3", "char_f12": "audio/modifiers/fun_12_ame.mp3", "char_arrowup": "audio/modifiers/mod_up_arrow_ame.mp3",
      "char_arrowdown": "audio/modifiers/mod_down_arrow_ame.mp3", "char_arrowleft": "audio/modifiers/mod_left_arrow_ame.mp3", "char_arrowright": "audio/modifiers/mod_right_arrow_ame.mp3",
      "char_insert": "audio/modifiers/mod_insert_ame.mp3", "char_delete": "audio/modifiers/mod_delete_ame.mp3", "char_home": "audio/modifiers/mod_home_ame.mp3",
      "char_end": "audio/modifiers/mod_end_ame.mp3", "char_pageup": "audio/modifiers/mod_page_up_ame.mp3", "char_pagedown": "audio/modifiers/mod_page_down_ame.mp3",
      "char_numlock": "audio/modifiers/mod_num_lock_ame.mp3", "char_clear": "audio/modifiers/mod_clear_ame.mp3", "char_printscreen": "audio/modifiers/mod_print_screen_ame.mp3",
      "char_scrolllock": "audio/modifiers/mod_scroll_lock_ame.mp3", "char_pause": "audio/modifiers/mod_pause_ame.mp3",

      // System Additions v2.6.2 (Alphabet & Row Words)
      "word_zenith": "audio/words/zenith_sn.mp3",
      "word_zone": "audio/words/zone_sn.mp3",
      "word_zephyr": "audio/words/zephyr_sn.mp3",
      "word_z_axis": "audio/words/z_axis_sn.mp3",
      "word_xenon": "audio/words/xenon_sn.mp3",
      "word_x_ray": "audio/words/x_ray_sn.mp3",
      "word_x_axis": "audio/words/x_axis_sn.mp3",
      "word_comms": "audio/words/comms_sn.mp3",
      "word_cargo": "audio/words/cargo_sn.mp3",
      "word_cryogenics": "audio/words/cryogenics_sn.mp3",
      "word_core": "audio/words/core_sn.mp3",
      "word_velocity": "audio/words/velocity_sn.mp3",
      "word_visuals": "audio/words/visuals_sn.mp3",
      "word_vector": "audio/words/vector_sn.mp3",
      "word_vacuum": "audio/words/vacuum_sn.mp3",
      "word_boosters": "audio/words/boosters_sn.mp3",
      "word_ballistics": "audio/words/ballistics_sn.mp3",
      "word_bulkheads": "audio/words/bulkheads_sn.mp3",
      "word_beacon": "audio/words/beacon_sn.mp3",
      "word_navigation": "audio/words/navigation_sn.mp3",
      "word_network": "audio/words/network_sn.mp3",
      "word_neutrino": "audio/words/neutrino_sn.mp3",
      "word_node": "audio/words/node_sn.mp3",
      "word_mainframe": "audio/words/mainframe_sn.mp3",
      "word_magnetics": "audio/words/magnetics_sn.mp3",
      "word_munitions": "audio/words/munitions_sn.mp3",
      "word_monitors": "audio/words/monitors_sn.mp3",
      "word_quantum": "audio/words/quantum_sn.mp3",
      "word_quasar": "audio/words/quasar_sn.mp3",
      "word_quarantine": "audio/words/quarantine_sn.mp3",
      "word_weapons": "audio/words/weapons_sn.mp3",
      "word_warp": "audio/words/warp_sn.mp3",
      "word_waypoint": "audio/words/waypoint_sn.mp3",
      "word_waveform": "audio/words/waveform_sn.mp3",
      "word_emitters": "audio/words/emitters_sn.mp3",
      "word_encryption": "audio/words/encryption_sn.mp3",
      "word_radar": "audio/words/radar_sn.mp3",
      "word_reactor": "audio/words/reactor_sn.mp3",
      "word_relays": "audio/words/relays_sn.mp3",
      "word_thrusters": "audio/words/thrusters_sn.mp3",
      "word_telemetry": "audio/words/telemetry_sn.mp3",
      "word_targeting": "audio/words/targeting_sn.mp3",
      "word_tachyeon": "audio/words/tachyeon_sn.mp3",
      "word_yaw": "audio/words/yaw_sn.mp3",
      "word_yield": "audio/words/yield_sn.mp3",
      "word_yoke": "audio/words/yoke_sn.mp3",
      "word_y_axis": "audio/words/y_axis_sn.mp3",
      "word_uplink": "audio/words/uplink_sn.mp3",
      "word_utilities": "audio/words/utilities_sn.mp3",
      "word_ultraviolet": "audio/words/ultraviolet_sn.mp3",
      "word_uhf": "audio/words/uhf_sn.mp3",
      "word_ignition": "audio/words/ignition_sn.mp3",
      "word_inertial": "audio/words/inertial_sn.mp3",
      "word_infrared": "audio/words/infrared_sn.mp3",
      "word_oxygen": "audio/words/oxygen_sn.mp3",
      "word_optics": "audio/words/optics_sn.mp3",
      "word_override": "audio/words/override_sn.mp3",
      "word_orbit": "audio/words/orbit_sn.mp3",
      "word_plasma": "audio/words/plasma_sn.mp3",
      "word_propulsion": "audio/words/propulsion_sn.mp3",
      "word_probes": "audio/words/probes_sn.mp3",
      "word_payload": "audio/words/payload_sn.mp3",

      // Commander Keyboard Hesitations (v3.22.0)
      "ck_mut_ack1": "audio/char/ack1_ck.mp3",
      "ck_mut_ack2": "audio/char/ack2_ck.mp3",
      "ck_mut_ah1":  "audio/char/ah1_ck.mp3",
      "ck_mut_ah2":  "audio/char/ah2_ck.mp3",
      "ck_mut_foo1": "audio/char/foo1_ck.mp3",
      "ck_mut_hmm1": "audio/char/hmm1_ck.mp3",
      "ck_mut_hmm2": "audio/char/hmm2_ck.mp3",
      "ck_mut_ick1": "audio/char/ick1_ck.mp3",
      "ck_mut_oh1":  "audio/char/oh1_ck.mp3",
      "ck_mut_oh2":  "audio/char/oh2_ck.mp3",
      "ck_mut_oh3":  "audio/char/oh3_ck.mp3",
      "ck_mut_umm1": "audio/char/umm1_ck.mp3",
      "ck_mut_umm2": "audio/char/umm2_ck.mp3",
      "ck_mut_umm3": "audio/char/umm3_ck.mp3",
      "ck_mut_umm4": "audio/char/umm4_ck.mp3",
      "ck_mut_woah1": "audio/char/woah1_ck.mp3",
      "ck_mut_woah2": "audio/char/woah2_ck.mp3",

      // Legacy BGM Registry (v3.23.1)
      "mu_default1": "audio/music/mu_default1.mp3",
      "mu_default2": "audio/music/mu_default2.mp3",
      "mu_default3": "audio/music/mu_default3.mp3",
      "mu_default4": "audio/music/mu_default4.mp3",
      "mu_spaghetti1": "audio/music/mu_spaghetti1.mp3",
      "mu_spaghetti2": "audio/music/mu_spaghetti2.mp3",
      "mu_spaghetti3": "audio/music/mu_spaghetti3.mp3",
      "mu_spaghetti4": "audio/music/mu_spaghetti4.mp3",

      // BGM Expansion (v3.23.0)
      "mu_default5": "audio/music/mu_default5.mp3",
      "mu_default6": "audio/music/mu_default6.mp3",
      "mu_default7": "audio/music/mu_default7.mp3",
      "mu_default8": "audio/music/mu_default8.mp3",
      "mu_spaghetti5": "audio/music/mu_spaghetti5.mp3",
      "mu_spaghetti6": "audio/music/mu_spaghetti6.mp3",
      "mu_spaghetti7": "audio/music/mu_spaghetti7.mp3",
      "mu_spaghetti8": "audio/music/mu_spaghetti8.mp3",
      "mu_arcade1": "audio/music/mu_arcade1.mp3",
      "mu_arcade2": "audio/music/mu_arcade2.mp3",
      "mu_arcade3": "audio/music/mu_arcade3.mp3",
      "mu_arcade4": "audio/music/mu_arcade4.mp3",
      "mu_arcade5": "audio/music/mu_arcade5.mp3",
      "mu_arcade6": "audio/music/mu_arcade6.mp3",
      "mu_arcade7": "audio/music/mu_arcade7.mp3",
      "mu_arcade8": "audio/music/mu_arcade8.mp3"
  },
  
  resources: [
      { id: "data_blocks", name: "Data Blocks", type: "currency", desc: "Raw encrypted data packets." },
      { id: "logic_shards", name: "Logic Shards", type: "material", desc: "Processing fragments for upgrades." },
      { id: "sync_sparks", name: "Sync Sparks", type: "currency", desc: "Energy from high-speed synchronization." },
      { id: "consecutive_coins", name: "Consecutive Coins", type: "currency", desc: "Tokens for perfect focus streaks." },
      { id: "glitch", name: "Glitch", type: "hazard", desc: "System corruption from input errors." }
  ],
  
  fabricator_recipes: [
      {
          category: "SYSTEM REPAIR",
          items: [
              { name: "Logic Purge", cost_val: 200, cost_type: "data_blocks", action: "clear_glitch", desc: "Removes all accumulated Glitch Mass." },
              { name: "Maintenance Patch", cost_val: 50, cost_type: "data_blocks", action: "add_item", item_key: "patches", desc: "Standard maintenance patch. Sent to inventory." }
          ]
      },
      {
          category: "SYSTEM UPGRADES",
          items: [
              { name: "Mystery Swap", cost_val: 10, cost_type: "glitch", action: "mystery_swap", desc: "Trade 10 Glitch for a random logic reward." },
              { name: "System Overclock", cost_val: 500, cost_type: "data_blocks", action: "add_item", item_key: "reflex_chip", desc: "Permanently reduces input latency for all systems." }
          ]
      }
  ],
  
  engineering: [
      {
          category: "MODULES",
          items: [
              { name: "Auto-Correct v1", cost_val: 500, cost_type: "logic_shards", action: "unlock_module", item_key: "auto_correct", desc: "Automatically corrects one typo per mission." },
              { name: "Shield Generator", cost_val: 1000, cost_type: "logic_shards", action: "unlock_module", item_key: "shields", desc: "Absorbs hazard damage once per mission." }
          ]
      }
  ],
  
  arcade: [
    {
        name: "Combat Training",
        items: [
            { name: "Reflex Calibration", target_id: "D00-MISSION-REFLEX", reward_est: 20, desc: "A standard reflex simulation for new cadets.", obj: "React to the system cues." },
            { name: "Password Decryption", target_id: "D00-MISSION-PASS", reward_est: 35, desc: "Simulated brute-force attack on a basic firewall.", obj: "Type the key sequences correctly." }
        ]
    }
  ],
  lore: []
};